# Nivell 1

## Exercici 1
**Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.**

In [11]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8], dtype = 'i8')
print(arr.dtype)
print(f"La dimensió del array és de {arr.ndim} dimensió")
print(f"Shape: {arr.shape}")

int64
La dimensió del array és de 1 dimensió
Shape: (8,)


## Exercici 2
**De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts.**

In [17]:
print(f"El valor mitjà és: {np.mean(arr)}")

El valor mitjà és: 4.5


## Exercici 3
**Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.**

In [76]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,9,8,7,6],[5,4,3,2,1],[5,2,7,8,1]])
arr2_O = np.sort(arr2)
arr2_O = np.hsplit(arr2_O, 5)
arr2_O = arr2_O[4].reshape(-1)
print(f"Valor màxim de cada eix: {arr2_O}")
arr2_O.sort()
print(f"El valor més gran de la matriu és: {arr2_O[-1]}")

Valor màxim de cada eix: [ 5 10 11  5  8]
El valor més gran de la matriu és: 11


# Nivell 2

## Exercici 4
**Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".**

In [80]:
arr1 = np.array([[4,6,2],[8,2,5],[8,3,1]])
arr2 = np.array([[4,6,2],[8,2,5],[8,3,1]])
arr3 = np.array([[4,6,2],[8,2,5]])
print(f"{arr1 * arr2}") 
print(f"{arr1 * arr3}") 

[[16 36  4]
 [64  4 25]
 [64  9  1]]


ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

## Exercici 5
**Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.**

In [79]:
arr1 = np.array([[4,6,2],[8,2,5],[8,3,1]])
arr1_col = np.array_split(arr1, 3, axis = 1)
arr1_col = arr1_col[1].reshape(-1)
print(f"Columna 2: {arr1_col}\nSuma: {sum(arr1_col)}")
print(f"Fila 1: {arr1[0]}\nSuma: {sum(arr1[0])}")

Columna 2: [6 2 3]
Suma: 11
Fila 1: [4 6 2]
Suma: 12


# Exercici 6
**Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.**

**Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.**